### ISSUE TITLE
A question about comparison experiment, why didn't you compare with CESTa on dailydialog dataset?

### ISSUE THREAD

**Issue by qftie** [rungjoo/CoMPM#4]
[Contextualized Emotion Recognition in Conversation as Sequence Tagging](https://aclanthology.org/2020.sigdial-1.23.pdf) seems to be one influential article in ERC area, I wonder that why didn't you compare with CESTa on dailydialog dataset? Is there any specific reason?

**Comment by rungjoo** [comment]
No. There is no particular reason.
When I wrote the paper, I cited mainly frameworks that were tested with the same evaluation metric in four benchmarks.
CESTa is also considered a good paper, but it was published in 2020. We cite more recent papers.

**Comment by qftie** [comment]
No offense, I just find it hard to reach cesta's micro performance of 63.12 on dailydialog, which is 3 points higher than compm, one of the most advanced models nowadays, so I would like to ask if there is a reason why this is not comparable due to different experimental settings or different metrics settings.
I was wondering if perhaps they only considered micro as a performance criterion and your experiments took into account both micro and macro scores, and if this could be the basis for not using the data reported in their paper for comparison.

**Comment by rungjoo** [comment]
CESTa was measured only with micro metrics in dailyDialog, and was not tested in EmoryNLP.
However, since CESTa shows good results in dailydialog, it is reasonable to select it as a comparative paper.

*caution*
I'm not fully aware of CESTa , but from a quick glance it seems that future utterances are taken into account as input. (Figure 2)
That is, if future utterances are considered input, they are not suitable as comparative papers. There are often studies that improve emotion recognition performance by using future utterances.
This is because typical ERC studies only use utterances before the current turn as context.
